### ISSUE TITLE
Issue with libpam.so.0 ?

### ISSUE THREAD

**Issue by jasonhargis** [gdubicki/centos-pam-with-update-motd#1]
Attempted to use this on CentOS Linux release 7.7.1908 (Core), but it appears there might be an issue with libpam.so.0 ...

$ yum install https://github.com/gdubicki/centos-pam-with-update-motd/releases/download/1.1.8-1022.3/pam-1.1.8-1022.el7.x86_64.rpm
Loaded plugins: fastestmirror, langpacks
pam-1.1.8-1022.el7.x86_64.rpm                                                                                | 726 kB  00:00:00
Examining /var/tmp/yum-root-9Ob7rX/pam-1.1.8-1022.el7.x86_64.rpm: pam-1.1.8-1022.el7.x86_64
Marking /var/tmp/yum-root-9Ob7rX/pam-1.1.8-1022.el7.x86_64.rpm as an update to pam-1.1.8-22.el7.x86_64
Marking /var/tmp/yum-root-9Ob7rX/pam-1.1.8-1022.el7.x86_64.rpm as an update to pam-1.1.8-22.el7.i686
Resolving Dependencies
--> Running transaction check
---> Package pam.i686 0:1.1.8-22.el7 will be updated
--> Processing Dependency: libpam.so.0 for package: systemd-libs-219-67.el7_7.2.i686
Loading mirror speeds from cached hostfile
 * base: mirrors.cat.pdx.edu
 * elrepo: repos.ord.lax-noc.com
 * epel: sjc.edge.kernel.org
 * extras: mirrors.unifiedlayer.com
 * rpmfusion-free-updates: muug.ca
 * rpmfusion-nonfree-updates: muug.ca
 * updates: repos.lax.layerhost.com
--> Processing Dependency: libpam.so.0(LIBPAM_1.0) for package: systemd-libs-219-67.el7_7.2.i686
--> Processing Dependency: libpam.so.0(LIBPAM_EXTENSION_1.0) for package: systemd-libs-219-67.el7_7.2.i686
--> Processing Dependency: libpam.so.0(LIBPAM_MODUTIL_1.0) for package: systemd-libs-219-67.el7_7.2.i686
--> Processing Dependency: libpam_misc.so.0 for package: systemd-libs-219-67.el7_7.2.i686
--> Processing Dependency: libpam_misc.so.0(LIBPAM_MISC_1.0) for package: systemd-libs-219-67.el7_7.2.i686
---> Package pam.x86_64 0:1.1.8-22.el7 will be updated
---> Package pam.x86_64 0:1.1.8-1022.el7 will be an update
--> Finished Dependency Resolution
Error: Package: systemd-libs-219-67.el7_7.2.i686 (@updates)
           Requires: libpam.so.0
           Removing: pam-1.1.8-22.el7.i686 (@base)
               libpam.so.0
           Updated By: pam-1.1.8-1022.el7.x86_64 (/pam-1.1.8-1022.el7.x86_64)
               Not found
 You could try using --skip-broken to work around the problem

**Comment by gdubicki** [comment]
Hey, sorry for lack of response, @jasonhargis, my GitHub notification settings were wrong and I have only noticed this issue a moment ago... I'll check it out over the weekend. Unless you already solved it? Please let me know.

**Comment by gdubicki** [comment]
Closing as I haven't noticed this issue on any machine I have tested this on. Please feel free to reopen if anyone observes this!
